groups:
  docker_hosts:
    - docker-01
    - docker-02
  agents:
    - agent-01

hosts:
  docker-01:
    host: 10.0.0.11
    user: root
    profile: docker_host
  docker-02:
    host: 10.0.0.12
    user: root
    profile: docker_host
  agent-01:
    host: 10.0.0.21
    user: root
    profile: agents
